IKProjesiAPI.UI/Models/ErrorViewModel.cs
namespace IKProjesiAPI.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

IKProjesiAPI.UI/Controllers/HomeController.cs
using IKProjesiAPI.Domain.Entities;
using IKProjesiAPI.Infrastructure.Context;
using IKProjesiAPI.UI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace IKProjesiAPI.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly AppDbContext _appDbContext;
        public HomeController(ILogger<HomeController> logger, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager, AppDbContext appDbContext)
        {
            _logger = logger;
            _userManager = userManager;
            _signInManager = signInManager;
            _appDbContext = appDbContext;
        }

        [AllowAnonymous]
        public ActionResult Login(string returnUrl = "/")
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            ViewData["returnUrl"] = returnUrl;
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            TempData["Success"] = "Kullanıcı Çıkışı Gerçekleştirildi.";
            _appDbContext.TemporaryPasswords.Remove(temporaryPassword);
            _appDbContext.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

IKProjesiAPI.UI/Controllers/MailController.cs
using IKProjesiAPI.Domain.Entities;
using IKProjesiAPI.Infrastructure.Context;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Net.Mail;

namespace IKProjesiAPI.UI.Controllers
{
    public class MailController : Controller
    {
        public AppDbContext _context;
        public MailController(AppDbContext context)
        {
            _context = context;
        }
        [HttpPost]
        public IActionResult GeciciSifre()
        {
            Guid newGuid = Guid.NewGuid();
            string guidString = newGuid.ToString();

            var temporaryPassword = new TemporaryPassword
            {
                Password = guidString
            };

            _context.TemporaryPasswords.Add(temporaryPassword);
            _context.SaveChanges();

            try
            {
                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.EnableSsl = true;
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = new NetworkCredential("arslanilkay06@gmail.com", "xbishuykxbcmashq");
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;

                MailMessage mail = new MailMessage();
                mail.From = new MailAddress("arslanilkay06@gmail.com");
                mail.To.Add(new MailAddress("arslanilkay06@gmail.com"));
                mail.Subject = "New GUID";
                mail.Body = guidString;

                smtp.Send(mail);

                ViewBag.Message = "E-posta başarıyla gönderildi.";
            }
            catch (Exception ex)
            {
                ViewBag.Message = "E-posta gönderilirken bir hata oluştu: " + ex.Message;
            }
            return null;
        }
    }
}

IKProjesiAPI.UI/Views/Home/Index.cshtml
@using IKProjesiAPI.Application.Models.DTOs
@model LoginDto

<div class="container-fluid mb-5 ">
    <div class="container-fluid pt-5 ">
        <div class="text-center mb-4">
            <h2 class="section-title px-5">
                <span class="px-2">Giriş Yap</span>
            </h2>
        </div>
        <div class="row px-xl-5">
            <div class="col-lg-7 mb-5 offset-3">
                <div class="contact-form">
                    <div id="success"></div>
                    <form asp-controller="Home" asp-action="Login" method="post" id="contactForm" novalidate="novalidate">
                        <div class="control-group">
                            <input asp-for="Email" class="form-control" placeholder="Kullanıcı E-Posta" required="required" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <br />
                        <div class="control-group">
                            <input asp-for="Password" type="password" class="form-control" placeholder="Şifre" required="required" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                        <br />
                        <div>
                            <button class="btn btn-primary py-2 px-4" type="submit" id="login">Giriş Yap</button>
                        </div>
                    </form>
                    <form method="post" asp-controller="Mail" asp-action="GeciciSifre">
                        <button class="btn btn-primary py-2 px-4" type="submit">Geçici Şifre Al</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

IKProjesiAPI.UI/Views/Home/Login.cshtml
@using IKProjesiAPI.Application.Models.DTOs
@model LoginDto
@{
    Layout = "_Layout";
}

<div class="container-fluid mb-5 ">
    <div class="container-fluid pt-5 ">
        <div class="text-center mb-4">
            <h2 class="section-title px-5">
                <span class="px-2">Giriş Yap</span>
            </h2>
        </div>
        <div class="row px-xl-5">
            <div class="col-lg-7 mb-5 offset-3">
                <div class="contact-form">
                    <div id="success"></div>
                    <form asp-controller="Home" asp-action="Index" method="post" id="contactForm" novalidate="novalidate">
                        <div class="control-group">
                            <input asp-for="Email" class="form-control" placeholder="Kullanıcı Adı" required="required" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <br />
                        <div class="control-group">
                            <input asp-for="Password" type="password" class="form-control" placeholder="Şifre" required="required" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                        <br />
                        <div>
                            <button class="btn btn-primary py-2 px-4" type="submit" id="logout">Çıkış Yap</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

IKProjesiAPI.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IKProjesiAPI.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IKProjesiAPI.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IKProjesiAPI.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - IKProjesiAPI.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>